### ISSUE TITLE
How i can install it&

### ISSUE THREAD

**Issue by Tesloz** [quizzr-cms/quizzr#2]
How i can install it&Where i can got bd dump?

**Comment by jophab** [comment]
@Tesloz This project is not complete.  This was our mini project at college.
Unfortunately we had lost the database data we worked with and the table schema.

So at present this is not usable. :disappointed: 
We are so sorry about this. 
Thanks for visiting and getting in touch.
we will try to come up with a better version in future :+1:

**Comment by gautamkrishnar** [comment]
@Tesloz Added the db file. 
### This is not a completed project. Please use it with precaution...
