### ISSUE TITLE
Errors on login page

### ISSUE THREAD

**Issue by ragasirtahk** [quizzr-cms/quizzr#3]
Notice: Use of undefined constant wu - assumed 'wu' in C:\xampp\htdocs\login.php on line 41

Notice: Undefined index: wu in C:\xampp\htdocs\login.php on line 41

I am new to web development so please tell how to fix this and where I am going wrong.

**Comment by jophab** [comment]
@alpha007khatri  its just a notice. Turn warnings off.
wu means wrong username and wp means wrong passsword.
It will have values when user enters a wrong user name or passwrod.

Also this project is not complete. The sql dump file is not available here because it contain real user data

**Comment by ragasirtahk** [comment]
Can you provide a dummy SQL dump file to test the project?
